### ISSUE TITLE
Watchdog caught collective operation timeout: WorkNCCL(SeqNum=2315, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1808543 milliseconds before timing out.

### ISSUE THREAD

**Issue by iamhappytoo** [tdrussell/qlora-pipe#19]
Hi @tdrussell,

First of all, thank you so much for your helpful discussion in another issue earlier! 
Now I am able to use qlora-pipe with deepspeed on two node environment with 12 * 80 GB GPUs for full parameter tuning of a 70b model using adamw_kahan optimizer. 
I'm using the hostfile like this:
node1 slots=4
node2 slots=8

The training works fine for first epoch and first several evaluation steps, but when it tries to save best_loss checkpoint, it hangs for 30min and then got timeout. 

The error log looks like this:
```
node04: [2024-07-12 19:13:00.439] [INFO] [qlora-pipe] step:  1400 /  2112 loss: 0.8146 iter time (s): 1.010 samples/sec: 0.990 eta: 11m53s 
node04: Running eval
node04: before GAS splitting, batch size: 1, total tokens: 1024
node04: before GAS splitting, batch size: 1, total tokens: 1024
node04: before GAS splitting, batch size: 1, total tokens: 1024
node04: before GAS splitting, batch size: 1, total tokens: 1024
node04: [E ProcessGroupNCCL.cpp:474] [Rank 7] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=5727, OpType=ALLREDUCE, NumelIn=1, NumelOut=1, Timeout(ms)=1800000) ran for 1800240 milliseconds before timing out.
node04: [E ProcessGroupNCCL.cpp:474] [Rank 6] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=5727, OpType=ALLREDUCE, NumelIn=1, NumelOut=1, Timeout(ms)=1800000) ran for 1800281 milliseconds before timing out.
node04: [E ProcessGroupNCCL.cpp:474] [Rank 5] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=5727, OpType=ALLREDUCE, NumelIn=1, NumelOut=1, Timeout(ms)=1800000) ran for 1800325 milliseconds before timing out.
node04: [E ProcessGroupNCCL.cpp:474] [Rank 4] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=5727, OpType=ALLREDUCE, NumelIn=1, NumelOut=1, Timeout(ms)=1800000) ran for 1800357 milliseconds before timing out.
node04: [E ProcessGroupNCCL.cpp:474] [Rank 3] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=5727, OpType=ALLREDUCE, NumelIn=1, NumelOut=1, Timeout(ms)=1800000) ran for 1800409 milliseconds before timing out.
node04: [E ProcessGroupNCCL.cpp:474] [Rank 2] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=5727, OpType=ALLREDUCE, NumelIn=1, NumelOut=1, Timeout(ms)=1800000) ran for 1800447 milliseconds before timing out.
node04: [E ProcessGroupNCCL.cpp:474] [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=5727, OpType=ALLREDUCE, NumelIn=1, NumelOut=1, Timeout(ms)=1800000) ran for 1800493 milliseconds before timing out.
node04: [E ProcessGroupNCCL.cpp:474] [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=5727, OpType=ALLREDUCE, NumelIn=1, NumelOut=1, Timeout(ms)=1800000) ran for 1800526 milliseconds before timing out.
```
I'm saving the checkpoints onto a nfs file system shared between the two nodes. I'm not sure if this is causing the timeout issue. The training dataset is pretty small, with only ~3million tokens, the evaluation dataset is around 0.1% size of the training dataset. I found some threads discussing similar things https://github.com/huggingface/accelerate/issues/314#issuecomment-1280485293 
https://github.com/axolotl-ai-cloud/axolotl/issues/967  Not sure if they are relevant.
Do you have some thoughts about what might be the potential reason/fix?
Thank you so much!
Looking forward to your reply!

**Comment by tdrussell** [comment]
I'm not sure what's going wrong. Unfortunately I don't have access to a multi-machine environment so I can't really debug anything. All the development I did for the code assumed single-machine training.

Are you using eval_before_first_step? Did it ever complete an eval and save the model? If training works but eval hangs at some point, I guess you would want to always trigger eval first and try to find what's wrong. You'd have to add prints / logs everywhere to try to figure out exactly at which line of code it's hanging at. I would try to debug this myself but without a multi-node setup there's no easy way for me to do that, so you're mostly on your own here.

**Comment by iamhappytoo** [comment]
Hi @tdrussell, many thanks for your helpful reply! By adjusting the settings of the multi-machine environment, especially the infiniband and nccl socket settings to appropriate values, I can run the multi-node training with qlora-pipe now. This practice confirms the train.py has no bug related to multi-node training.

**Comment by jukofyork** [comment]
I've got this working now too - It was surprisingly easy to set up:

- You can setup `model =`(and `dataset_path =` if needed) to be a local copy of each model so no need to send it through the network.
- The `output_dir = ` needs to be shared.

I used this to help me setup the `/job/hostfile` file:

https://nlp.stanford.edu/mistral/tutorials/deepspeed.html

and you can setup Passwordless SSH as explained here:

https://linuxize.com/post/how-to-setup-passwordless-ssh-login/

You can mix `pipeline_stages = ` to use pipeline parallel per node too (don't try between-node  pipeline parallel unless you have something like InfiniBand as the amount getting passed will really add up quickly...)

It doesn't seem to use much network bandwidth for the LoRA all-reduce step, but for full fine-tuning it would use a huge amount...

I'll try and put in a PR for the readme file to explain this better if I get chance.

**Comment by jukofyork** [comment]
I'll add it to here in case anyone else comes across this, as I doubt it will be possible to track down the cause:

Using multiple `[[datasets]]` in a `config.toml` seems to cause a memory leak on the non-rank-0 machines when doing multinode training.

All 3 machines have 512GB of RAM, but rank-1 and rank-2 used it all and then started using 100s of GB of swapfile whilst preparing the data.

When I included just two `[[datasets]]` in a `config.toml` then rank-1 and rank-2 did eventually finish the preprocessing and successfully trained, but using three `[[datasets]] cause the machines to lock up eventually.
